# Generated by Django 2.0 on 2019-05-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('edition', models.IntegerField()),
                ('category', models.CharField(choices=[('Electronics', 'ECE'), ('Computers', 'CSE'), ('Civil', 'CIVIL'), ('Human Resources', 'HR'), ('Finance', 'FIN'), ('Marketing', 'MKT')], max_length=20)),
                ('publisher', models.CharField(max_length=50)),
                ('reviews', models.FloatField()),
                ('available', models.CharField(choices=[('Yes', 'Y'), ('No', 'N')], max_length=5)),
                ('issued_date', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateTimeField()),
            ],
        ),
    ]
